services:
  app:
    image: ${IMAGE_NAME}
    build:
      context: .
      dockerfile: Dockerfile.dev
    init: true
    volumes:
      - type: bind
        source: "."
        target: "/root/catsay"
    ports:
        - 4242:3000

  redis:
    image: redis:7.2-alpine
