FROM debian:12.1

RUN apt-get update --quiet --yes
RUN apt-get install --quiet --yes curl less vim
RUN apt-get install --quiet --yes ruby-full build-essential

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
  apt-get install --quiet --yes nodejs

RUN gem install bundler

COPY .bashrc.dx.local /root/.bashrc.dx.local
RUN echo "# Dev-specific Bash customizations" >> ~/.bashrc && \
  echo ". ./.bashrc.dx.local" >> ~/.bashrc

WORKDIR /root/catsay

CMD sleep infinity
