#!/usr/bin/env bash

set -e
set -o pipefail

dirname=$(dirname -- "${0}")
script_dir=$(cd -- "${dirname}" > /dev/null 2>&1 && pwd)
\. ${script_dir}/shared.lib.sh

usage() {
  echo "Usage: ${0} [-h]"
  echo ""
  echo "Builds the development Docker image from Dockerfile.dev"
  echo ""
  echo "OPTIONS"
  echo ""
  echo "  -h - show this help"
}

while getopts ":h" opt "${@}"; do
  case ${opt} in
    h)
      usage
      exit 0
      ;;
    \?)
      log "Invalid option: ${OPTARG}"
      usage
      exit 1
      ;;
  esac
done
shift $((OPTIND - 1))

check_for_docker

log "Stopping dev environment"
docker compose \
  --file "${root_dir}"/compose.dev.yml \
  --env-file "${script_dir}"/.env \
  down

log "Dev environment stopped successfully!"
